defaults: &defaults
    # Required.
    api_key: d021704a60cc8bc40f75e2b6378d4234
    secret_key: bb79555f0450db437536df6f008a4194
    
    # Optional for Facebook Connect.
    # canvas_page_name: YOUR_APP_CANVAS_NAME
    # Optional for Facebook Connect. Depends on your Facebook App settings.
    callback_url: http://localhost:3000
    
    # Optional options.
    pretty_errors: true
    set_asset_host_to_callback_url: false
    tunnel:
      public_host_username: 
      public_host: 
      public_port: 4007
      local_port: 3000
    
development:
  <<: *defaults
  
test: &test
  <<: *defaults
  
production: &production
  <<: *defaults
  
# staging:
#   <<: *production
# 
# cucumber:
#   <<: *test